theme = "slick"
icons = "awesome"

[[block]]
block = "backlight"
device = "intel_backlight"


[[block]]
block = "battery"
interval = 10
show = "both"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 10.0
alert = 1.5

[[block]]
block = "disk_space"
path = "/media/storage"
alias = "storage"
info_type = "available"
unit = "GB"
interval = 20
warning = 50.0
alert = 10.0

[[block]]
block = "net"
device = "wlan0"
ssid = true
ip = true
speed_up = false
graph_up = true
interval = 5

[[block]]
block = "speedtest"
bytes = true
interval = 1800

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "temperature"
collapsed = true
interval = 30
format = "{min}° min, {max}° max, {average}° avg"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "uptime"

[[block]]
block = "sound"

[[block]]
block = "pacman"

[[block]]
block = "time"
interval = 60
format = "%a %F %R"

